### ISSUE TITLE
Please move the ESLint thing to the HTML/JS Section.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#1]
I would prefer to find the ESLint option insde the HTML/JS tab. Think about it, I think that would be a better place for this.

**Comment by Chris2011** [comment]
I can make a pull request, if you don't have time.

**Comment by joakim-eriksson** [comment]
I agree. Pull request is always welcome, otherwise it will be fixed in one or two days anyway.
