### ISSUE TITLE
NB-ESLint should bring a default, global lint file with it

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#10]
When I install eslint into VS code, I don't need to config everything. It immediately shows me warnings/errors in my JS file. I don't need to set global file.

So this case is simple, nb-eslint, should bring a default, global rule file with some common settings and should use this file. If you don't want to use this file, you can change it inside the options. If you have an local .eslintrc in your project, then this should be used.

So case 2 and 3 are working, case 1 is nor implemented. A default file with a couple of rules, is better than to have nothing. Now I have to find a default file by myself. This is not, what I need in the VS Code extension.

Cheers

Chris

**Comment by joakim-eriksson** [comment]
I think if you can enable and disable this on a project basis a default file could be generated once you enable it.

**Comment by Chris2011** [comment]
Atm it will use the config file from the project, if there is no config file, it will do nothing. If you still want to use it, you need to provide a file by your own and check the checkbox "Use custom config". For this, we can deliver one with default stuff. Will do this later.

**Comment by Chris2011** [comment]
I will skip this. I think if they click on custom config file they should provide one by their own. If we still want this feature someone else can reopen this ticket.
