### ISSUE TITLE
Add a search button after the browse button

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#11]
In node, bower, npm, gulp, node, grunt etc. there is a search button right after the browse button, so you don't need to find the execution by your own. So it would be handy and what is more important consistent to the other options. How you can scan for the executable, you can find it here: https://github.com/Chris2011/NBAngularCLI/blob/master/src/net/chrizzly/netbeans/plugins/nbangularcli/ui/options/AngularCliOptionsPanel.java#L126

To make it even more consistent to all other options, you can make the input field full size. I mean of course it is a type of taste but IMHO it should be consistent with each other.

Cheers

Chris

**Comment by joakim-eriksson** [comment]
I agree.

**Comment by Chris2011** [comment]
Pleaes have a look into the PR.

**Comment by Chris2011** [comment]
Implemented.

**Comment by Chris2011** [comment]
Can you please make a new release? @joakim-eriksson

**Comment by joakim-eriksson** [comment]
New version has been released :)
