### ISSUE TITLE
Underline the errors instead of change the background.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#17]
It depends on the look and feel you have, but if you color the background of the column, it could be, that you can't see the character behind the color or it looks mor dificult. Every other stuff in NetBeans will underline your code, if there is a problem. So please be consistent with NetBeans and underline the errors, instead of coloring the background.

Cheers

Chris

**Comment by joakim-eriksson** [comment]
I will see what I can do and when I will have the time.

**Comment by Chris2011** [comment]
You have to use `--format json` to get the json and then you will get `range:12:15` for example. So you will get startLine/startColumn, endLine/endColumn. range could be the column, the rest needs a bit research.

**Comment by Chris2011** [comment]
But everything what you need to know is inside the other format.

**Comment by Chris2011** [comment]
I don't know the NetBeans API good enough to know whether it is possible or not. I just see the linepart which changes the background of one character or the whole line, which is not that nice.

**Comment by Chris2011** [comment]
Finally I get it working. See #41. Will merge it soon. 3 years after I created this ticket :D. Better late then never.

**Comment by Chris2011** [comment]
Done via release 1.5.0.
