### ISSUE TITLE
Add an option to enable/disable eslint

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#18]
I don't want to activate/deactivate the plugin, because I have to restart my IDE (After deactivation). So it would be nice, if you can add an option to enable/disable eslint of scanning for errors, if you don't need it. It would be good to have a global option for hat and to have a project specific option for that.

Cheers

Chris

**Comment by joakim-eriksson** [comment]
Thanks, Chris for your dedicated feedback and yes this could be useful I guess.

**Comment by Chris2011** [comment]
Will do this globally in the first round.

**Comment by Chris2011** [comment]
Done in 1.4.0
