### ISSUE TITLE
Nothing happens, don't know how to use.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#2]
I installed the package via npm -g install eslint. I added the .cmd file and a config but nothing happens. I don't know how to use it :/. Can you give an example please?

**Comment by joakim-eriksson** [comment]
Are you using windows?

Could you try to run it from the command line like

/usr/bin/eslint --config /some/path/.eslintrc --format compact .

in a project that have some errors and give me the output.

**Comment by joakim-eriksson** [comment]
Will try to test more on windows. are you using the full path like C:\Users\xxx\AppData\Roaming\eslint

use double back slashes

**Comment by Chris2011** [comment]
Have to test it later. Will give you feedback soon.

**Comment by dumith-eranga** [comment]
Hi @joakim-eriksson 
I have the same issue in Windows.
I configured the ESLint path to "{full_path}\eslint.js" under Tools > Options > Miscellaneous > ESLint and pointed the Conf path to a valid ".eslintrc" file. But I do not see any changes to editor when I have invalid JS code as per the config file rules.

**Comment by Chris2011** [comment]
Had no time yet, sry. Will help you to give you the info, what you need @joakim-eriksson

**Comment by joakim-eriksson** [comment]
You need to use the cmd file. On my friends computer it looks like this.
C:\Users\${userName}\AppData\Roaming\npm\eslint.cmd

So please try to run it from the command line first.

**Comment by Chris2011** [comment]
This is the property: C:\Users\chrl\AppData\Roaming\npm\eslint.cmd So everything is fine. Yes I will try from the command line. Will give you feedback later.

**Comment by dumith-eranga** [comment]
@joakim-eriksson 
It's working fine now that I set the path to the cmd file.
Thank you for this really useful plug-in.

**Comment by joakim-eriksson** [comment]
Great news! Please let me know if you are missing any functionality or want to change any behavior.

**Comment by Chris2011** [comment]
I created a comment there: https://github.com/walmartlabs/eslint-config-defaults/issues/43

there you can read what happend, when I call:

```
C:\Users\chrl\AppData\Roaming\npm\eslint.cmd --config .eslintrc.json --format compact .
```

from the command line.

**Comment by Chris2011** [comment]
Ok I fixed that, the problem was this inside my .eslintrc.json file:

```
{
   "extends": "google"
}
```

thx. After changing a file and saving this file, eslint will execute. Will be good, I think as it is. For other things, I will create other tickets.

**Comment by joakim-eriksson** [comment]
Ok thanks I will try to make the problem easier to debug.
