### ISSUE TITLE
Please release 1.1.1

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#27]
Hey, as figured out, inside of the plugin portal: http://plugins.netbeans.org/plugin/63486/eslint there is still the old nb-eslint 1.0 version. But with my changes etc. we are at 1.1.1. Please make a new release and update the plugin portal nbm file. And add it here to github to the release section. Thx :)

**Comment by ssilvert** [comment]
But please merge my PR first.  :-)

**Comment by joakim-eriksson** [comment]
Fixed
