### ISSUE TITLE
Please add option for project eslint config file.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#3]
Atm, you can only add a eslintrc file globally, I think for all projects. So often it is needed that you have a eslintrc file for each project. The same as bower.json and package.json and jslint.rc. So for this, you need a option inside the properties section of a clientside project to set a config file for this project.

Regards

Chris

**Comment by joakim-eriksson** [comment]
I agree. Will fix in the next version.

If .eslintrc exists in project that will be used.

**Comment by joakim-eriksson** [comment]
if you have a .eslintrc in the root of the project that one will be used, Otherwise it fallbacks to global configuration. Let me know if that is a implementation that works for you.

**Comment by Chris2011** [comment]
Many thx, yeah this should work for me. I will test it soon.
