### ISSUE TITLE
Adding hacktoberfest topic to your repo.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#33]
Can you please add the hacktoberfest to your repo? That would be great. Here is the info how to do that: https://hacktoberfest.digitalocean.com/hacktoberfest-update.

**Comment by Chris2011** [comment]
Can you please add it, otherwise my PRs will not count for the Hacktoberfest event.

**Comment by joakim-eriksson** [comment]
Done
