### ISSUE TITLE
Add all errors into the Action item window.

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#4]
Usually, all infos, errors, warnings can be found into the Action Item window. But your entries are not there. Please add all errors into the action item window to filter for only the opened file or for all files.

**Comment by joakim-eriksson** [comment]
Should work. what version do you have installed.

**Comment by Chris2011** [comment]
Ok I see, I set a filter, sorry for that. Was my fault.

**Comment by Chris2011** [comment]
Everything is fine.
