### ISSUE TITLE
Please add option/menu entry to analyse all js files or a project

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#5]
It would be very nice to have a context menu entry called "Analyze -> ESLint" or so for a project, for each JS files which will be found in this project, to analyze all JS files and got a list/tree view with all errors inside a new window called analyze or so. That would be great.

**Comment by joakim-eriksson** [comment]
If you open the Action Items window they should be listed there. And the you can select current file or current project or all projects.

**Comment by joakim-eriksson** [comment]
Let me know if this works for you.

**Comment by Chris2011** [comment]
It is ok, I can life with that.

**Comment by Chris2011** [comment]
I would like to reopen the ticket, because ESLint can be the same as Inspect for the project. This is possible for Java and PHP projects so you can right click a project and inspect and choose FIndBugs for example. So ESLint should be added to the inspect section.

If this is not possible with a 3rd-party-plugin, then it should be an action for the project like: `Scan with ESLint` or smth like that.
