### ISSUE TITLE
Please add JSCS support

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#6]
I know that this is a plugin to support eslint but first I think JSCS isn't that different from eslint. So it I think you can reuse a lot of logic for this to create either a new plugin nb-jscs or to implement jscs into the eslint plugin. As I read this article today: http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint
jscs is now part of the eslint team, but it works both similar.

Regards

Chris

**Comment by joakim-eriksson** [comment]
There will be no more releases of JSCS. So I see no point in starting to add support for it now. Do you have to use JSCS?.

**Comment by Chris2011** [comment]
Hm ok, I see the point. No, I don't have to. I wanted to test both but I didn't know that both are similiar to each other. New fancy stuff you know? Thought both are different. Thx.
